apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 245007448664.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 245007448664.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 62bd5382
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
